services:
  ms-backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - devops-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/unit_test_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      
  mysql-db:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - devops-net  
    environment:
      MYSQL_DATABASE: unit_test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: My-admin-pw
      MYSQL_ROOT_PASSWORD: My-secret-pw
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:

networks:
  devops-net: